---


- name: Install gitbook using npm
  npm:
    name: gitbook-cli
    global: yes

- name: Create install path
  file:
    path: "{{item.path}}"
    state: directory
  with_items: gitbook_books

#- name: Download books from git
#  git:
#    repo: "{{item.repo|default('https://github.com/GitbookIO/documentation')}}"
#    dest: "{{item.path}}"
#    recursive: yes
#    force: yes
#    update: yes
#    clone: yes
#    accept_hostkey: yes
#    key_file: /etc/ssh/ssh_host_rsa_key
#  with_items: gitbook_books

- name: Add systemd service
  template:
    src: "gitbook.service.j2"
    dest: "/etc/systemd/system/gitbook-{{item.name}}.service"
  with_items: gitbook_books
  notify: reload systemd

- name: Ensure services are started
  service:
    name: "gitbook-{{item.name}}"
    state: started
    enabled: yes
  with_items: gitbook_books

- pause:
    seconds: 10

# TODO: Fix this rubbish
# Bug workaround in gitbook

- file:
    path: "{{item.path}}/_book/books/{{item.bugfix}}"
    state: directory
  with_items: gitbook_books

- command: "mv {{item.path}}/_book/index.html {{item.path}}/_book/books/{{item.bugfix}}/index.html"
  with_items: gitbook_books

- command: "mv {{item.path}}/_book/gitbook {{item.path}}/_book/books/{{item.bugfix}}/gitbook"
  with_items: gitbook_books

- command: "mv {{item.path}}/_book/search_index.json {{item.path}}/_book/books/{{item.bugfix}}/search_index.json"
  with_items: gitbook_books
