---


- name: Install gitbook using npm
  npm:
    name: gitbook-cli
    global: yes

- name: Create install path
  file:
    path: "{{item.path}}"
    state: directory
  with_items: gitbook_books

#- name: Download books from git
#  git:
#    repo: "{{item.repo|default('https://github.com/GitbookIO/documentation')}}"
#    dest: "{{item.path}}"
#    recursive: yes
#    force: yes
#    update: yes
#    clone: yes
#    accept_hostkey: yes
#    key_file: /etc/ssh/ssh_host_rsa_key
#  with_items: gitbook_books

- name: Add systemd service
  template:
    src: "gitbook.service.j2"
    dest: "/etc/systemd/system/gitbook-{{item.name}}.service"
  with_items: gitbook_books
  notify: reload systemd

- name: Ensure services are started
  service:
    name: "gitbook-{{item.name}}"
    state: started
    enabled: yes
  with_items: gitbook_books

# Temporary fix for web1.prd.davison.io
# TODO: Permanent fix

- name: Bugfix in gitbook 1
  cron:
    name: gitbook bugfix 1
    job: "mkdir /var/www/davisonio/books/gcse-science/_book/books && mkdir /var/www/davisonio/books/gcse-science/_book/books/gcse-science && cp -a /var/www/davisonio/books/gcse-science/_book/. /var/www/davisonio/books/gcse-science/_book/books/gcse-science/"
    state: present

- name: Bugfix in gitbook 2
  cron:
    name: gitbook bugfix 2
    job: "mkdir /var/www/davisonio/books/gcse-geography/_book/books && mkdir /var/www/davisonio/books/gcse-geography/_book/books/gcse-geography && cp -a /var/www/davisonio/books/gcse-geography/_book/. /var/www/davisonio/books/gcse-geography/_book/books/gcse-geography/"
    state: present

- name: Bugfix in gitbook 3
  cron:
    name: gitbook bugfix 3
    job: "mkdir /var/www/davisonio/books/gcse-religious-studies/_book/books && mkdir /var/www/davisonio/books/gcse-religious-studies/_book/books/gcse-religious-studies && cp -a /var/www/davisonio/books/gcse-religious-studies/_book/. /var/www/davisonio/books/gcse-religious-studies/_book/books/gcse-religious-studies/"
    state: present

- name: Bugfix in gitbook 4
  cron:
    name: gitbook bugfix 4
    job: "mkdir /var/www/davisonio/books/gcse-mathematics/_book/books && mkdir /var/www/davisonio/books/gcse-mathematics/_book/books/gcse-mathematics && cp -a /var/www/davisonio/books/gcse-mathematics/_book/. /var/www/davisonio/books/gcse-mathematics/_book/books/gcse-mathematics/"
    state: present

- name: Bugfix in gitbook 5
  cron:
    name: gitbook bugfix 5
    job: "mkdir /var/www/davisonio/books/gcse-german/_book/books && mkdir /var/www/davisonio/books/gcse-german/_book/books/gcse-german && cp -a /var/www/davisonio/books/gcse-german/_book/. /var/www/davisonio/books/gcse-german/_book/books/gcse-german/"
    state: present

- name: Bugfix in gitbook 6
  cron:
    name: gitbook bugfix 6
    job: "mkdir /var/www/davisonio/books/gcse-english/_book/books && mkdir /var/www/davisonio/books/gcse-english/_book/books/gcse-english && cp -a /var/www/davisonio/books/gcse-english/_book/. /var/www/davisonio/books/gcse-english/_book/books/gcse-english/"
    state: present

- name: Bugfix in gitbook 7
  cron:
    name: gitbook bugfix 7
    job: "mkdir /var/www/davisonio/books/gcse-computer-science/_book/books && mkdir /var/www/davisonio/books/gcse-computer-science/_book/books/gcse-computer-science && cp -a /var/www/davisonio/books/gcse-computer-science/_book/. /var/www/davisonio/books/gcse-computer-science/_book/books/gcse-computer-science/"
    state: present
