---

- name: Make sure the ntp is installed
  apt:
    name: ntp
    state: present

- name: Fetch leapseconds file
  get_url:
    url: "{{ntp_leapurl}}"
    dest: "/etc/ntp.leapseconds"
    owner: "root"
    group: "root"
    mode: "0660"

- name: Configure ntp (/etc/ntp.conf)
  template:
    src: ntp.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
