- name: Add Nginx PPA
  apt_repository:
    repo: ppa:nginx/development
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Copy h5bp configs
  copy:
    src: templates/h5bp
    dest: "{{ nginx_path }}"
  notify: reload nginx

- name: Create nginx.conf
  template:
    src: "nginx.conf"
    dest: "{{ nginx_path }}/nginx.conf"
  notify: reload nginx

- name: Disable default server
  file:
    path: "{{ nginx_path }}/sites-enabled/default"
    state: absent
  notify: reload nginx

- name: Add unknown site
  template:
    src: "sites/unknown.j2"
    dest: "/etc/nginx/sites-available/unknown"
  notify: reload nginx

- name: Enable unknown site
  file:
    path: "/etc/nginx/sites-enabled/unknown"
    src: "/etc/nginx/sites-available/unknown"
    state: link
  notify: reload nginx

- name: Add sites
  template:
    src: "sites/{{item}}.j2"
    dest: "/etc/nginx/sites-available/{{item}}"
  with_items: "{{nginx_sites}}"
  notify: reload nginx

- name: Enable sites
  file:
    path: "/etc/nginx/sites-enabled/{{item}}"
    src: "/etc/nginx/sites-available/{{item}}"
    state: link
  with_items: "{{nginx_sites}}"
  notify: reload nginx

- name: Add simple pages
  template:
    src: "simple/{{ item.type }}.j2"
    dest: "{{ item.path }}"
  with_items: "{{ nginx_index_pages }}"

- name: Enable Nginx to start on boot
  service:
    name: nginx
    enabled: yes
    state: started
    use: service
