- name: Add stable Nginx PPA
  apt_repository:
    repo: ppa:nginx/stable
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Allow Nginx in UFW
  ufw:
    rule: allow
    name: Nginx Full

- name: Copy h5bp configs
  copy:
    src: templates/h5bp
    dest: /etc/nginx
  notify: restart nginx

- name: Add nginx.conf
  template:
    src: "nginx.conf"
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Add mime.types
  template:
    src: "mime.types"
    dest: /etc/nginx/mime.types
  notify: restart nginx

- name: Add unknown site
  template:
    src: "conf.d/unknown.conf"
    dest: "/etc/nginx/conf.d/unknown.conf"
  notify: restart nginx

- name: Add sites
  template:
    src: "conf.d/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
  with_items: "{{ nginx_sites }}"
  notify: restart nginx
