---

- name: Update the hostname (hostname cmd)
  hostname:
    name: "{{inventory_hostname}}"

- name: Update the hostname (/etc/hostname)
  template:
    src: hostname.j2
    dest: /etc/hostname

- name: Update the IPv4 hostname (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{inventory_hostname}} {{inventory_hostname_short}} localhost"
    state: present

- name: Update the IPv6 hostname (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1 {{inventory_hostname}} {{inventory_hostname_short}} localhost ip6-localhost ip6-loopback"
    state: present
