language: python

python:
  # Ansible does not support python 3 so we'll be testing on the latest python 2 release
  - 2.7.11

before_install:
  # Use latest version of pip because travis usually contains an old release
  - pip install --upgrade pip

install:
  - pip install ansible

script:
  # Run all our roles to check their syntax
  - "cd tests && ansible-playbook test.yml --syntax-check"

notifications:
  email: false
