- name: Apply base tasks
  hosts: app:base
  roles:
    - timezone
    - ntp
    - users
    - sudo
    - hostname
    - apt
    - openssh
    - updates

- name: Apply minetest tasks
  hosts: app:minetest
  roles:
    - minetest

- name: Apply nginx tasks
  hosts: app:nginx
  roles:
    - nginx
    - letsencrypt

- name: Apply backup tasks
  hosts: app:backup
  roles:
    - backup

- name: Apply gitbook tasks
  hosts: app:gitbook
  roles:
    - nodejs
    - gitbook

- name: Apply jekyll tasks
  hosts: app:jekyll
  roles:
    - ruby
    - jekyll
