- name: Base
  hosts: all
  roles:
      - users
      - ssh
      - apt
      - ufw
  tasks:
  - name: Set timezone
    timezone:
      name: Europe/London

- import_playbook: plays/minetest1.yml
- import_playbook: plays/wp1.yml
- import_playbook: plays/eurodiscover.yml
