---

- name: Make sure apt is installed
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - python-apt
    - aptitude
    - apt
    - apt-utils

- name: Update the apt cache
  apt:
    update_cache=yes

- name: Install repositories
  apt_repository:
    repo="{{ item }}"
    update_cache=yes
  with_items: apt_install_repositories

- name: Remove repositories
  apt_repository:
    repo="{{ item }}"
    state=absent
    update_cache=yes
  with_items: apt_remove_repositories

- name: Upgrade all packages
  apt:
    upgrade={{ apt_upgrade_type }}
    update_cache=yes

- name: Install packages
  apt:
    pkg="{{ item }}"
    state=present
  with_flattened:
    - apt_install
    - apt_install_host

- name: Remove packages
  apt:
    pkg="{{ item }}"
    state=absent
  with_flattened:
    - apt_remove
    - apt_remove_host
