- name: Install packages
  apt:
    name: aptitude
    state: present

- name: Install repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_install_repositories }}"

- name: Update packages
  apt:
      update_cache: yes
      allow_unauthenticated: yes
  changed_when: False

- name: Install packages
  apt:
    name: "{{ query('flattened', ['{{ apt_install }}', '{{ apt_install_group }}', '{{ apt_install_host }}']) }}"
    state: present

- name: Upgrade packages
  apt:
    upgrade: safe

- name: Autoremove packages
  apt:
      autoremove: yes
