---

nginx_sites:
  - name: davisonio
  - name: default
  - name: craigydaviukto
  - name: space2staycom
  - name: flimrcom

nginx_sites_enabled:
  - default
  - davisonio
  - craigydaviukto
  - space2staycom
  - flimrcom

ghost_location: /var/www/davisonio/blog
