minetest_location: /usr/share/minetest/

minetest_games:
  - name: "Craig-Server_game"
    url: "https://github.com/davisonio/Craig-Server_game"

minetest_instances:
  - name: server

minetest_secret_settings: []
