---

- name: Install nodejs + npm packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nodejs
    - npm
    # https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory
    - nodejs-legacy
