- name: Ensure restic directories exist
  file:
    state: 'directory'
    path: '{{ item }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '/var/log/restic'
    - '{{ restic_download_path }}/bin'

- name: Check if binary is present
  stat:
    path: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
  register: restic_executable

- name: Install restic
  include: 'install.yml'
  when: not restic_executable.stat.exists

- name: Create B2_ACCOUNT_ID
  cronvar:
    name: B2_ACCOUNT_ID
    value: "{{ restic_b2_account_id }}"

- name: Create B2_ACCOUNT_KEY
  cronvar:
    name: B2_ACCOUNT_KEY
    value: "{{ restic_b2_account_key }}"

- name: Create RESTIC_PASSWORD
  cronvar:
    name: RESTIC_PASSWORD
    value: "{{ restic_password }}"

- name: Configuring restic jobs
  cron:
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  with_items: "{{ restic_jobs }}"
