---

apt_enabled: no

apt_cache_valid_time: 3600
apt_update: true

apt_upgrade: true
apt_upgrade_type: safe          # safe, full or dist

apt_dependencies:
  - python-apt
  - aptitude
  - apt
  - apt-utils

apt_install:
  - rsync
  - curl
  - git
  - python

apt_install_repositories: false

apt_remove_repositories: false

apt_remove: false
