---

apt_cache_valid_time: 3600
apt_update: true

apt_upgrade: true
apt_upgrade_type: safe          # safe, full or dist

apt_install:
  - rsync
  - curl
  - git
  - python
  - nano-tiny

apt_install_host: []

apt_install_repositories:
  - "ppa:minetestdevs/daily-builds"

apt_remove_repositories: false

apt_remove: false
