- name: Install dependancies
  pip:
    name: TwitterFollowBot
    state: latest

- name: Create directory
  file:
    path: /etc/twitterfollowbot
    state: directory

- name: Install TwitterFollowBot
  git:
    repo: https://github.com/rhiever/TwitterFollowBot
    dest: /etc/twitterfollowbot
    force: yes
    accept_hostkey: yes

- name: Add script
  template:
    src: twitterfollowbot.py.j2
    dest: "/etc/twitterfollowbot/twitterfollowbot.py"
#  notify:
#    - stop scripts
#    - start scripts

- name: Add configs
  template:
    src: config.txt.j2
    dest: "/etc/twitterfollowbot/{{ item.key }}-config.txt"
  with_dict: "{{ twitterfollowbot_scripts }}"

#- name: Set script to re-run daily
#  cron:
#    name: "twitterfollowbot"
#    job: "pkill -f twitterfollowbot.py & python /etc/twitterfollowbot/twitterfollowbot.py >> /etc/twitterfollowbot/twitterfollowbot.log"
#    special_time: reboot
#  with_items: twitterfollowbot_scripts
