---


- name: Check if index.js exists in ghost location
  stat:
    path: "{{ghost_location}}/index.js"
  register: indexjs

- name: Download latest release of ghost
  get_url:
    url: https://ghost.org/zip/ghost-latest.zip
    dest: /tmp/ghost-latest.zip
  when: indexjs.stat.exists == False

- name: Create install location
  file:
    path: "{{ghost_location}}"
    state: directory
  when: indexjs.stat.exists == False

- name: Unzip ghost to install location
  unarchive:
    copy: no
    # TODO; when 2.0 is stable change this to ghost.org/zip/ghost-latest.zip
    src: "/tmp/ghost-latest.zip"
    dest: "{{ghost_location}}"
  when: indexjs.stat.exists == False

- name: Install node dependancies
  npm:
    path: "{{ghost_location}}"
    production: yes

- name: Configure ghost
  template:
    src: config.js.j2
    dest: "{{ghost_location}}/config.js"
  notify:
    - restart ghost

- name: Add systemd service
  template:
    src: "ghost.service.j2"
    dest: /etc/systemd/system/ghost.service
  notify:
    - reload systemd

- name: Ensure service is started
  service:
    name: ghost.service
    state: started
    enabled: yes
