- name: Create SSH directory
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
  with_items: "{{ users_users }}"

- name: Add users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    password: "{{ item.pass | default(omit) }}"
    shell: /bin/bash
    state: present
  with_items: "{{ users_users }}"

- name: Copy root authorized_keys to user
  copy:
    src: /root/.ssh/authorized_keys
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    remote_src: yes
  with_items: "{{ users_users }}"
