- name: Make sure sudo is installed
  apt:
    name: sudo
    state: latest

- name: Update sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
