- hosts: panda
  tasks:
  - include_role:
      name: common
  - include_role:
      name: certbot
  - include_role:
      name: nginx


# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
# nvm install --lts
# sudo apt install nginx
# sudo ufw allow 'Nginx Full'
# sudo apt install mariadb-server mariadb-client
# npm i -g ghost-cli
# mkdir /var/www/davison.io
# chown craig:craig /var/www/davison.io
# chmod 777 /var/www/davison.io


# might have nvm permissions errors
# regular stuff to sort out: dist upgrades, reboots, ghost updates, node updates, npm updates using npm install -g npm
# manage bashrc
