- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: "yes"

- name: Create wheel group
  group:
    name: wheel

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create base user in wheel group
  user:
    name: "{{ create_user }}"
    groups: wheel
    append: true
    shell: /bin/bash

- name: Get root authorized keys
  command: cat /root/.ssh/authorized_keys
  register: root_authorized_keys
  changed_when: false

- name: Set authorized key for base user
  authorized_key:
    user: "{{ create_user }}"
    key: "{{ root_authorized_keys.stdout }}"

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Install base packages
  apt:
    name: "{{ base_packages }}"

- name: Allow SSH in UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Deny incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming
