nginx_sites:
  - name: davison.io
  - name: default
  - name: space2stay.com
  - name: flimr.com

nginx_sites_enabled:
  - default
  - davison.io
  - space2stay.com
  - flimr.com

jekyll_sites:
  - name: davisonio
    path: /var/www/davison.io
    repo: https://github.com/davisonio/davison.io

letsencrypt_sites:
  - davison.io

duplicity_profiles:
  - name: main
