nginx_sites:
  - name: davison.io
  - name: default
  - name: space2stay.com
  - name: flimr.com
  - name: space2park.org.uk
  - name: tutoring.co.uk

nginx_sites_enabled:
  - default
  - davison.io
  - space2stay.com
  - flimr.com
  - space2park.org.uk
  - tutoring.co.uk

jekyll_sites:
  - name: davisonio
    path: /var/www/davison.io
    repo: https://github.com/davisonio/davison.io
  - name: space2parkorguk
    path: /var/www/space2park.org.uk
    repo: git@github.com:davisonio/space2park.org.uk.git
    key: /etc/ssh/ssh_host_rsa_key_space2parkorguk
  - name: flimrcom
    path: /var/www/flimr.com
    repo: git@github.com:davisonio/flimr.com.git
    key: /etc/ssh/ssh_host_rsa_key_flimrcom
  - name: space2staycom
    path: /var/www/space2stay.com
    repo: git@github.com:davisonio/space2stay.com.git
    key: /etc/ssh/ssh_host_rsa_key_space2staycom
  - name: tutoringcouk
    path: /var/www/tutoring.co.uk
    repo: git@github.com:davisonio/tutoring.co.uk.git
    key: /etc/ssh/ssh_host_rsa_key_tutoringcouk

letsencrypt_sites:
  - davison.io
  - flimr.com
  - space2stay.com
  - space2park.org.uk
  - tutoring.co.uk

duplicity_profiles:
  - name: main
